### ISSUE TITLE
Choosing a specific `styler` style

### ISSUE THREAD

**Issue by pat-s** [lorenzwalthert/pre-commit-hooks#20]
Would be great if this hook could support `options(styler.addins_style_transformer)` or a similar global setting.

**Comment by lorenzwalthert** [comment]
You can pass arguments to hooks, either in the cli or set them in `.pre-commit-config.yaml`.  `autopep8-wrapper` described in https://pre-commit.com/hooks.html is one. Need to investigate.

**Comment by lorenzwalthert** [comment]
The relevant section is here: https://pre-commit.com/#passing-arguments-to-hooks

**Comment by pat-s** [comment]
I don't have capacities atm to investigate this further. Thanks for your effort in this!

**Comment by lorenzwalthert** [comment]
Ok, I might then.

**Comment by lorenzwalthert** [comment]
I think I am almost there but the problem is that ideally, we pass the `style` argument to the bash script via `.pre-commit-config.yaml`: 

```yaml
repos:
-   repo: https://github.com/lorenzwalthert/pre-commit-hooks
    rev: v0.0.0.9009
    hooks: 
    -   id: style-files
        args: [--style='oneliner::one_line_style']

```
Which results in an error 

```An error has occurred: InvalidConfigError:
==> File .pre-commit-config.yaml
=====> while scanning a plain scalar
  in "<unicode string>", line 6, column 16
found unexpected ':'
  in "<unicode string>", line 6, column 33
```

which is a false positive from what I can tell, at least it seems unneded when `:` occurs in a string. We could of course try to circumvent the problem by using any special character and then translating it back to `::` (which I think is very hacky), or use two arguments (one for the package and one for the function)  to resolve the argument and then *build* `packagename::functionname` out of it.
